# Generated by Django 4.2.3 on 2023-07-27 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_profile_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='username',
            new_name='soubriquet',
        ),
    ]
