# Generated by Django 4.2.3 on 2023-08-07 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_rename_username_profile_soubriquet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='soubriquet',
            new_name='username',
        ),
    ]
